# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/MIPS-CPU/MIPS-CPU/MIPS-CPU.srcs/sources_1/ip/blk_mem_ram_byte/blk_mem_ram_byte.xci
# IP: The module: 'blk_mem_ram_byte' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/MIPS-CPU/MIPS-CPU/MIPS-CPU.gen/sources_1/ip/blk_mem_ram_byte/blk_mem_ram_byte_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ram_byte'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: h:/MIPS-CPU/MIPS-CPU/MIPS-CPU.srcs/sources_1/ip/blk_mem_ram_byte/blk_mem_ram_byte.xci
# IP: The module: 'blk_mem_ram_byte' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/MIPS-CPU/MIPS-CPU/MIPS-CPU.gen/sources_1/ip/blk_mem_ram_byte/blk_mem_ram_byte_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ram_byte'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
