# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/MIPS-CPU/MIPS-CPU/MIPS-CPU.srcs/sources_1/ip/mult_gen_unsigned/mult_gen_unsigned.xci
# IP: The module: 'mult_gen_unsigned' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/MIPS-CPU/MIPS-CPU/MIPS-CPU.gen/sources_1/ip/mult_gen_unsigned/mult_gen_unsigned_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_unsigned'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: h:/MIPS-CPU/MIPS-CPU/MIPS-CPU.srcs/sources_1/ip/mult_gen_unsigned/mult_gen_unsigned.xci
# IP: The module: 'mult_gen_unsigned' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/MIPS-CPU/MIPS-CPU/MIPS-CPU.gen/sources_1/ip/mult_gen_unsigned/mult_gen_unsigned_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_unsigned'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
