create_clock -name board_clk -period 10.000 [get_ports board_clk]

# -----------------------------------------------------------------------------
# Clock constraints (fix timing/methodology)
# -----------------------------------------------------------------------------
# 1) 避免 clocking IP 内部的 create_clock（会在层级 pin 上创建主时钟，触发 TIMING-27）
catch {remove_clocks [get_clocks -quiet -of_objects [get_pins -quiet u_clocking/clk_in1]]}

# 2) 明确约束 clocking IP 输出的派生时钟（Vivado 在某些情况下可能不会正确推导分频比）
set _cpu_clk_pin [get_pins -quiet u_clocking/cpu_clk]
if {[llength $_cpu_clk_pin]} {
  catch {remove_clocks [get_clocks -quiet -of_objects $_cpu_clk_pin]}
  create_clock -name cpu_clk -period 200.000 $_cpu_clk_pin
}

set _uart_clk_pin [get_pins -quiet u_clocking/uart_clk]
if {[llength $_uart_clk_pin]} {
  catch {remove_clocks [get_clocks -quiet -of_objects $_uart_clk_pin]}
  create_clock -name uart_clk -period 100.000 $_uart_clk_pin
}

# 3) 半拍时钟（cpu_clk 取反）用于 ROM/RAM/外设：优先按 generated clock 建模；失败则退化为普通 clock
set _cpu_clk_n_net [get_nets -quiet cpu_clk_n]
if {[llength $_cpu_clk_n_net]} {
  catch {remove_clocks [get_clocks -quiet -of_objects $_cpu_clk_n_net]}
  if {[catch {create_generated_clock -name cpu_clk_n -source [get_clocks cpu_clk] -invert $_cpu_clk_n_net}]} {
    create_clock -name cpu_clk_n -period 200.000 $_cpu_clk_n_net
  }
}

# 4) CDC：UART 升级域与 CPU 域为异步关系（跨域信号已用握手/同步处理）
catch {set_clock_groups -asynchronous -group [get_clocks uart_clk] -group [get_clocks {cpu_clk cpu_clk_n}]}
catch {set_clock_groups -asynchronous -group [get_clocks board_clk] -group [get_clocks {cpu_clk cpu_clk_n uart_clk}]}
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_data_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_data_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_data_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_data_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_sel_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_sel_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_sel_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_sel_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_sel_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_sel_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_sel_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits_sel_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_cols_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_cols_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_cols_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_cols_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_rows_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_rows_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_rows_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_rows_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_GLD_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_GLD_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_GLD_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_GLD_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_GLD_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_GLD_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_GLD_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_GLD_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_RLD_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_RLD_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_RLD_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_RLD_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_RLD_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_RLD_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_RLD_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_RLD_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_YLD_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_YLD_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_YLD_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_YLD_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_YLD_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_YLD_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_YLD_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_YLD_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports beep_out]
set_property IOSTANDARD LVCMOS33 [get_ports board_clk]
set_property IOSTANDARD LVCMOS33 [get_ports board_rst]
set_property PACKAGE_PIN Y18 [get_ports board_clk]
set_property PACKAGE_PIN K17 [get_ports {led_RLD_out[7]}]
set_property PACKAGE_PIN L13 [get_ports {led_RLD_out[6]}]
set_property PACKAGE_PIN M13 [get_ports {led_RLD_out[5]}]
set_property PACKAGE_PIN K14 [get_ports {led_RLD_out[4]}]
set_property PACKAGE_PIN K13 [get_ports {led_RLD_out[3]}]
set_property PACKAGE_PIN M20 [get_ports {led_RLD_out[2]}]
set_property PACKAGE_PIN N20 [get_ports {led_RLD_out[1]}]
set_property PACKAGE_PIN N19 [get_ports {led_RLD_out[0]}]
set_property PACKAGE_PIN M17 [get_ports {led_YLD_out[7]}]
set_property PACKAGE_PIN M16 [get_ports {led_YLD_out[6]}]
set_property PACKAGE_PIN M15 [get_ports {led_YLD_out[5]}]
set_property PACKAGE_PIN K16 [get_ports {led_YLD_out[4]}]
set_property PACKAGE_PIN L16 [get_ports {led_YLD_out[3]}]
set_property PACKAGE_PIN L15 [get_ports {led_YLD_out[2]}]
set_property PACKAGE_PIN L14 [get_ports {led_YLD_out[1]}]
set_property PACKAGE_PIN J17 [get_ports {led_YLD_out[0]}]
set_property PACKAGE_PIN F21 [get_ports {led_GLD_out[7]}]
set_property PACKAGE_PIN G22 [get_ports {led_GLD_out[6]}]
set_property PACKAGE_PIN G21 [get_ports {led_GLD_out[5]}]
set_property PACKAGE_PIN D21 [get_ports {led_GLD_out[4]}]
set_property PACKAGE_PIN E21 [get_ports {led_GLD_out[3]}]
set_property PACKAGE_PIN D22 [get_ports {led_GLD_out[2]}]
set_property PACKAGE_PIN E22 [get_ports {led_GLD_out[1]}]
set_property PACKAGE_PIN A21 [get_ports {led_GLD_out[0]}]
set_property PACKAGE_PIN P20 [get_ports board_rst]
set_property PACKAGE_PIN R1 [get_ports {buttons_in[4]}]
set_property PACKAGE_PIN P1 [get_ports {buttons_in[3]}]
set_property PACKAGE_PIN P5 [get_ports {buttons_in[2]}]
set_property PACKAGE_PIN P4 [get_ports {buttons_in[1]}]
set_property PACKAGE_PIN P2 [get_ports {buttons_in[0]}]
set_property PACKAGE_PIN Y19 [get_ports rx]
set_property PACKAGE_PIN V18 [get_ports tx]
set_property PACKAGE_PIN A19 [get_ports beep_out]
set_property PACKAGE_PIN Y9 [get_ports {switches_in[23]}]
set_property PACKAGE_PIN W9 [get_ports {switches_in[22]}]
set_property PACKAGE_PIN Y7 [get_ports {switches_in[21]}]
set_property PACKAGE_PIN Y8 [get_ports {switches_in[20]}]
set_property PACKAGE_PIN AB8 [get_ports {switches_in[19]}]
set_property PACKAGE_PIN AA8 [get_ports {switches_in[18]}]
set_property PACKAGE_PIN V8 [get_ports {switches_in[17]}]
set_property PACKAGE_PIN V9 [get_ports {switches_in[16]}]
set_property PACKAGE_PIN AB6 [get_ports {switches_in[15]}]
set_property PACKAGE_PIN AB7 [get_ports {switches_in[14]}]
set_property PACKAGE_PIN V7 [get_ports {switches_in[13]}]
set_property PACKAGE_PIN AA6 [get_ports {switches_in[12]}]
set_property PACKAGE_PIN Y6 [get_ports {switches_in[11]}]
set_property PACKAGE_PIN T6 [get_ports {switches_in[10]}]
set_property PACKAGE_PIN R6 [get_ports {switches_in[9]}]
set_property PACKAGE_PIN V5 [get_ports {switches_in[8]}]
set_property PACKAGE_PIN U6 [get_ports {switches_in[7]}]
set_property PACKAGE_PIN W5 [get_ports {switches_in[6]}]
set_property PACKAGE_PIN W6 [get_ports {switches_in[5]}]
set_property PACKAGE_PIN U5 [get_ports {switches_in[4]}]
set_property PACKAGE_PIN T5 [get_ports {switches_in[3]}]
set_property PACKAGE_PIN T4 [get_ports {switches_in[2]}]
set_property PACKAGE_PIN R4 [get_ports {switches_in[1]}]
set_property PACKAGE_PIN W4 [get_ports {switches_in[0]}]
set_property PACKAGE_PIN K3 [get_ports {keyboard_cols_in[3]}]
set_property PACKAGE_PIN L3 [get_ports {keyboard_cols_in[2]}]
set_property PACKAGE_PIN J4 [get_ports {keyboard_cols_in[1]}]
set_property PACKAGE_PIN K4 [get_ports {keyboard_cols_in[0]}]
set_property PACKAGE_PIN L5 [get_ports {keyboard_rows_out[3]}]
set_property PACKAGE_PIN J6 [get_ports {keyboard_rows_out[2]}]
set_property PACKAGE_PIN K6 [get_ports {keyboard_rows_out[1]}]
set_property PACKAGE_PIN M2 [get_ports {keyboard_rows_out[0]}]
set_property PACKAGE_PIN A18 [get_ports {digits_sel_out[7]}]
set_property PACKAGE_PIN A20 [get_ports {digits_sel_out[6]}]
set_property PACKAGE_PIN B20 [get_ports {digits_sel_out[5]}]
set_property PACKAGE_PIN E18 [get_ports {digits_sel_out[4]}]
set_property PACKAGE_PIN F18 [get_ports {digits_sel_out[3]}]
set_property PACKAGE_PIN D19 [get_ports {digits_sel_out[2]}]
set_property PACKAGE_PIN E19 [get_ports {digits_sel_out[1]}]
set_property PACKAGE_PIN C19 [get_ports {digits_sel_out[0]}]
set_property PACKAGE_PIN E13 [get_ports {digits_data_out[7]}]
set_property PACKAGE_PIN C15 [get_ports {digits_data_out[6]}]
set_property PACKAGE_PIN C14 [get_ports {digits_data_out[5]}]
set_property PACKAGE_PIN E17 [get_ports {digits_data_out[4]}]
set_property PACKAGE_PIN F16 [get_ports {digits_data_out[3]}]
set_property PACKAGE_PIN F14 [get_ports {digits_data_out[2]}]
set_property PACKAGE_PIN F13 [get_ports {digits_data_out[1]}]
set_property PACKAGE_PIN F15 [get_ports {digits_data_out[0]}]
